import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import styles from '../styles/Home.module.css';
import gql from '../utils/gql';

type PropsGraphQLResponse = {
  data: {
    products: {
      nodes: {
        title: string;
      }[];
    };
  };
};

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch(`${process.env.API_URL}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Shopify-Storefront-Access-Token': `${process.env.ACCESS_TOKEN}`
    },
    body: JSON.stringify({
      query: gql`
        query ProductsQuery {
          products(first: 6) {
            nodes {
              title
            }
          }
        }
      `
    })
  });

  const { data }: PropsGraphQLResponse = await response.json();

  return {
    props: {
      data
    }
  };
};

type HomeProps = PropsGraphQLResponse;

// eslint-disable-next-line arrow-body-style
const Home: NextPage<HomeProps> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js + Shopify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js + Shopify!</h1>

        <div className={styles.grid}>
          {data.products.nodes.map((product) => (
            <div key={product.title} className={styles.card}>
              <h2>{product.title}</h2>
            </div>
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
